name: 'Action GitMerge'
description: 'Native Github action to make merge and deploy from repo.'
inputs:
  token:
    description: 'Github API token'
  pull-requests-base-branch:
    default: 'master'
    description: 'Name of base branch'
  merge-push-on:
    default: 'sdx'
    description: 'Name of branch will be created from base branch to merge PRs'


runs:
  using: 'docker'
  image: 'Dockerfile'
