name: 'Action GitMerge'
description: 'Native Github action to make merge and deploy from repo.'
inputs:
  token:
    description: 'Github API token'
  base:
    default: 'sdx'
    description: 'Name of base branch'
  work-branch-name:
    default: 'sdx-prs-deploy'
    description: 'Name of branch will be created from base branch to merge PRs'


runs:
  using: 'docker'
  image: 'Dockerfile'
